--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-04 11:50:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "DEVOLUCIONES";
--
-- TOC entry 4907 (class 1262 OID 16449)
-- Name: DEVOLUCIONES; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "DEVOLUCIONES" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es-ES';


ALTER DATABASE "DEVOLUCIONES" OWNER TO postgres;

\connect "DEVOLUCIONES"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16451)
-- Name: dv; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dv;


ALTER SCHEMA dv OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16491)
-- Name: addresses; Type: TABLE; Schema: dv; Owner: postgres
--

CREATE TABLE dv.addresses (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    department character varying(255),
    email character varying(255) NOT NULL
);


ALTER TABLE dv.addresses OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16490)
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: dv; Owner: postgres
--

ALTER TABLE dv.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dv.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16453)
-- Name: clients; Type: TABLE; Schema: dv; Owner: postgres
--

CREATE TABLE dv.clients (
    id bigint NOT NULL,
    document character varying(255) NOT NULL,
    document_type character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL
);


ALTER TABLE dv.clients OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16452)
-- Name: clients_id_seq; Type: SEQUENCE; Schema: dv; Owner: postgres
--

CREATE SEQUENCE dv.clients_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dv.clients_id_seq OWNER TO postgres;

--
-- TOC entry 4908 (class 0 OID 0)
-- Dependencies: 218
-- Name: clients_id_seq; Type: SEQUENCE OWNED BY; Schema: dv; Owner: postgres
--

ALTER SEQUENCE dv.clients_id_seq OWNED BY dv.clients.id;


--
-- TOC entry 4748 (class 2604 OID 16461)
-- Name: clients id; Type: DEFAULT; Schema: dv; Owner: postgres
--

ALTER TABLE ONLY dv.clients ALTER COLUMN id SET DEFAULT nextval('dv.clients_id_seq'::regclass);


--
-- TOC entry 4901 (class 0 OID 16491)
-- Dependencies: 221
-- Data for Name: addresses; Type: TABLE DATA; Schema: dv; Owner: postgres
--



--
-- TOC entry 4899 (class 0 OID 16453)
-- Dependencies: 219
-- Data for Name: clients; Type: TABLE DATA; Schema: dv; Owner: postgres
--



--
-- TOC entry 4909 (class 0 OID 0)
-- Dependencies: 220
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: dv; Owner: postgres
--

SELECT pg_catalog.setval('dv.addresses_id_seq', 1, false);


--
-- TOC entry 4910 (class 0 OID 0)
-- Dependencies: 218
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: dv; Owner: postgres
--

SELECT pg_catalog.setval('dv.clients_id_seq', 1, false);


--
-- TOC entry 4752 (class 2606 OID 16497)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: dv; Owner: postgres
--

ALTER TABLE ONLY dv.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 4750 (class 2606 OID 16463)
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: dv; Owner: postgres
--

ALTER TABLE ONLY dv.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


-- Completed on 2025-04-04 11:50:57

--
-- PostgreSQL database dump complete
--

