--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-04 11:53:15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "EMPRESARIOS";
--
-- TOC entry 4926 (class 1262 OID 16547)
-- Name: EMPRESARIOS; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "EMPRESARIOS" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es-ES';


ALTER DATABASE "EMPRESARIOS" OWNER TO postgres;

\connect "EMPRESARIOS"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16549)
-- Name: em; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA em;


ALTER SCHEMA em OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 16566)
-- Name: addresses; Type: TABLE; Schema: em; Owner: postgres
--

CREATE TABLE em.addresses (
    id integer NOT NULL,
    address character varying(200) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    email character varying(150)
);


ALTER TABLE em.addresses OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16565)
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: em; Owner: postgres
--

CREATE SEQUENCE em.addresses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE em.addresses_id_seq OWNER TO postgres;

--
-- TOC entry 4927 (class 0 OID 0)
-- Dependencies: 222
-- Name: addresses_id_seq; Type: SEQUENCE OWNED BY; Schema: em; Owner: postgres
--

ALTER SEQUENCE em.addresses_id_seq OWNED BY em.addresses.id;


--
-- TOC entry 219 (class 1259 OID 16551)
-- Name: customers; Type: TABLE; Schema: em; Owner: postgres
--

CREATE TABLE em.customers (
    id integer NOT NULL,
    document character varying(50) NOT NULL,
    document_type character varying(50) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL
);


ALTER TABLE em.customers OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16550)
-- Name: customers_id_seq; Type: SEQUENCE; Schema: em; Owner: postgres
--

CREATE SEQUENCE em.customers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE em.customers_id_seq OWNER TO postgres;

--
-- TOC entry 4928 (class 0 OID 0)
-- Dependencies: 218
-- Name: customers_id_seq; Type: SEQUENCE OWNED BY; Schema: em; Owner: postgres
--

ALTER SEQUENCE em.customers_id_seq OWNED BY em.customers.id;


--
-- TOC entry 225 (class 1259 OID 16575)
-- Name: address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address (
    id bigint NOT NULL,
    address character varying(255),
    city character varying(255),
    country character varying(255),
    email character varying(255),
    state character varying(255)
);


ALTER TABLE public.address OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16574)
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16558)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    document character varying(255),
    documenttype character varying(255),
    firstname character varying(255),
    lastname character varying(255)
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16557)
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4759 (class 2604 OID 16569)
-- Name: addresses id; Type: DEFAULT; Schema: em; Owner: postgres
--

ALTER TABLE ONLY em.addresses ALTER COLUMN id SET DEFAULT nextval('em.addresses_id_seq'::regclass);


--
-- TOC entry 4758 (class 2604 OID 16554)
-- Name: customers id; Type: DEFAULT; Schema: em; Owner: postgres
--

ALTER TABLE ONLY em.customers ALTER COLUMN id SET DEFAULT nextval('em.customers_id_seq'::regclass);


--
-- TOC entry 4918 (class 0 OID 16566)
-- Dependencies: 223
-- Data for Name: addresses; Type: TABLE DATA; Schema: em; Owner: postgres
--



--
-- TOC entry 4914 (class 0 OID 16551)
-- Dependencies: 219
-- Data for Name: customers; Type: TABLE DATA; Schema: em; Owner: postgres
--



--
-- TOC entry 4920 (class 0 OID 16575)
-- Dependencies: 225
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4916 (class 0 OID 16558)
-- Dependencies: 221
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4929 (class 0 OID 0)
-- Dependencies: 222
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: em; Owner: postgres
--

SELECT pg_catalog.setval('em.addresses_id_seq', 1, false);


--
-- TOC entry 4930 (class 0 OID 0)
-- Dependencies: 218
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: em; Owner: postgres
--

SELECT pg_catalog.setval('em.customers_id_seq', 1, false);


--
-- TOC entry 4931 (class 0 OID 0)
-- Dependencies: 224
-- Name: address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.address_id_seq', 1, false);


--
-- TOC entry 4932 (class 0 OID 0)
-- Dependencies: 220
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_id_seq', 1, false);


--
-- TOC entry 4765 (class 2606 OID 16573)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: em; Owner: postgres
--

ALTER TABLE ONLY em.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 4761 (class 2606 OID 16556)
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: em; Owner: postgres
--

ALTER TABLE ONLY em.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- TOC entry 4767 (class 2606 OID 16581)
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);


--
-- TOC entry 4763 (class 2606 OID 16564)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


-- Completed on 2025-04-04 11:53:15

--
-- PostgreSQL database dump complete
--

