--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-04 11:54:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "NOVIAS";
--
-- TOC entry 4907 (class 1262 OID 16528)
-- Name: NOVIAS; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "NOVIAS" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es-ES';


ALTER DATABASE "NOVIAS" OWNER TO postgres;

\connect "NOVIAS"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16529)
-- Name: nov; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA nov;


ALTER SCHEMA nov OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16531)
-- Name: customers; Type: TABLE; Schema: nov; Owner: postgres
--

CREATE TABLE nov.customers (
    id integer NOT NULL,
    document character varying(50) NOT NULL,
    document_type character varying(50) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    address character varying(200),
    city character varying(100),
    state character varying(100),
    country character varying(100),
    email character varying(150)
);


ALTER TABLE nov.customers OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16530)
-- Name: customers_id_seq; Type: SEQUENCE; Schema: nov; Owner: postgres
--

CREATE SEQUENCE nov.customers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE nov.customers_id_seq OWNER TO postgres;

--
-- TOC entry 4908 (class 0 OID 0)
-- Dependencies: 218
-- Name: customers_id_seq; Type: SEQUENCE OWNED BY; Schema: nov; Owner: postgres
--

ALTER SEQUENCE nov.customers_id_seq OWNED BY nov.customers.id;


--
-- TOC entry 221 (class 1259 OID 16540)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    address character varying(255),
    city character varying(255),
    country character varying(255),
    document character varying(255),
    documenttype character varying(255),
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    state character varying(255)
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16539)
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4748 (class 2604 OID 16534)
-- Name: customers id; Type: DEFAULT; Schema: nov; Owner: postgres
--

ALTER TABLE ONLY nov.customers ALTER COLUMN id SET DEFAULT nextval('nov.customers_id_seq'::regclass);


--
-- TOC entry 4899 (class 0 OID 16531)
-- Dependencies: 219
-- Data for Name: customers; Type: TABLE DATA; Schema: nov; Owner: postgres
--



--
-- TOC entry 4901 (class 0 OID 16540)
-- Dependencies: 221
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4909 (class 0 OID 0)
-- Dependencies: 218
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: nov; Owner: postgres
--

SELECT pg_catalog.setval('nov.customers_id_seq', 1, false);


--
-- TOC entry 4910 (class 0 OID 0)
-- Dependencies: 220
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_id_seq', 1, false);


--
-- TOC entry 4750 (class 2606 OID 16538)
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: nov; Owner: postgres
--

ALTER TABLE ONLY nov.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- TOC entry 4752 (class 2606 OID 16546)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


-- Completed on 2025-04-04 11:54:28

--
-- PostgreSQL database dump complete
--

